# render.yaml

services:
  - type: web
    name: discord-server-cloner
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python channel_copier.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    healthCheckPath: /
